### ISSUE TITLE
why not to remove foreach dependency in favor of for in?

### ISSUE THREAD

**Issue by xgbuils** [ljharb/is-typed-array#25]
Hi!

In this project `foreach` is used for traversing plain objects. Then, I guess that using `for in` there is a way  to do the same and, then, to remove `foreach` dependency that could be useful for traversing indistinctly arraylike and own key objects but not, in this case.

**Comment by ljharb** [comment]
`for..in` has bugs in many engines, and is not a good coding practice.

Indeed, in this case, I'm using it just to traverse the own keys of two internal objects. I'm also utilizing the scope that the foreach callback is creating, so even with `for..in` i'd want to call a function.

It's a small dependency, and more dependencies is better - what would the benefit be to remove it?

**Comment by xgbuils** [comment]
I like dependencies. But I think more dependencies is not always better. For example, if a dependency does not bring any benefit for the dependency consumer, why should it be imported?

In this case:

``` javascript
forEach(typedArrays, function (_, typedArray) {
//...
})
// ...
forEach(toStrTags, function (getter, typedArray) {
    //...
})
```

it could be replaced by:

``` javascript
for(var typedArray in typedArrays) {
    //...
}
// ...
for(var typedArray in toStrTags) {
    var getter = toStrTags[typedArray];
    //...
})
```

without any increment of code in the project.

On the other hand, I don't know if `for..in` has many bugs traversing literal objects in many engines.

**Comment by ljharb** [comment]
Your replacement is broken; it'd also have to have an "own property" check to avoid hitting enumerable things in `Object.prototype`.

**Comment by xgbuils** [comment]
That you say, is for preventing the implementation of some library that put enumerable properties on `Object.prototype`? or there is some engine that put enumerable properties on `Object.prototype`?

**Comment by xgbuils** [comment]
That you say, is for preventing the implementation of some library that put enumerable properties on Object.prototype? or is there some engine that put enumerable properties on Object.prototype?

**Comment by ljharb** [comment]
Yes, user code might do it.

**Comment by xgbuils** [comment]
Ok! thanks
